import { BadRequestException, NotFoundException } from '@nestjs/common';
import { describe, expect, it, vi } from 'vitest';
import type { AuditService } from '../audit/audit.service.js';
import type { PrismaService } from '../prisma/prisma.service.js';
import { AdministrationService } from './administration.service.js';
const org = '11111111-1111-4111-8111-111111111111'; const user = { id: '22222222-2222-4222-8222-222222222222', email: 'admin@example.com', roles: [], organizationIds: [org], permissions: ['organizations:manage'] };
describe('AdministrationService', () => {
  it('prevents self-deactivation', async () => { const prisma = { organization: { findUnique: vi.fn().mockResolvedValue({ id: org }) } }; await expect(new AdministrationService(prisma as unknown as PrismaService, {} as AuditService).setActive(org, user.id, false, user)).rejects.toBeInstanceOf(BadRequestException); });
  it('does not update a member without organization access', async () => { const prisma = { organization: { findUnique: vi.fn().mockResolvedValue({ id: org }) }, user: { findFirst: vi.fn().mockResolvedValue(null) } }; await expect(new AdministrationService(prisma as unknown as PrismaService, {} as AuditService).setActive(org, '33333333-3333-4333-8333-333333333333', false, user)).rejects.toBeInstanceOf(NotFoundException); });
  it('does not expose platform administrator as an assignable organization role', async () => { const prisma = { organization: { findUnique: vi.fn().mockResolvedValue({ id: org }) }, user: { findFirst: vi.fn().mockResolvedValue({ id: 'member', isActive: true }) }, role: { findFirst: vi.fn().mockResolvedValue(null) } }; await expect(new AdministrationService(prisma as unknown as PrismaService, {} as AuditService).assignRole(org, '33333333-3333-4333-8333-333333333333', '44444444-4444-4444-8444-444444444444', user)).rejects.toBeInstanceOf(NotFoundException); expect(prisma.role.findFirst).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ code: { not: 'PLATFORM_ADMIN' } }) })); });
  it('assigns an organization-scoped role and records audit evidence', async () => { const audit = { record: vi.fn().mockResolvedValue(undefined) }; const prisma = { organization: { findUnique: vi.fn().mockResolvedValue({ id: org }) }, user: { findFirst: vi.fn().mockResolvedValue({ id: 'member', isActive: true }) }, role: { findFirst: vi.fn().mockResolvedValue({ id: 'role', code: 'AUDITOR', name: 'Auditor' }) }, userRole: { create: vi.fn().mockResolvedValue({ id: 'assignment' }) } }; await expect(new AdministrationService(prisma as unknown as PrismaService, audit as unknown as AuditService).assignRole(org, '33333333-3333-4333-8333-333333333333', '44444444-4444-4444-8444-444444444444', user)).resolves.toEqual({ id: 'assignment' }); expect(prisma.userRole.create).toHaveBeenCalledWith({ data: { userId: '33333333-3333-4333-8333-333333333333', roleId: 'role', organizationId: org } }); expect(audit.record).toHaveBeenCalledWith(expect.objectContaining({ action: 'USER_ROLE_ASSIGNED', after: expect.objectContaining({ roleCode: 'AUDITOR' }) })); });
});
