-- Additive auditable matching and exception persistence.
CREATE TYPE "ExceptionStatus" AS ENUM ('OPEN', 'ASSIGNED', 'PROPOSED', 'APPROVED', 'RESOLVED');
CREATE TYPE "ExceptionSeverity" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
CREATE TABLE "reconciliation_matches" ("id" UUID NOT NULL, "reconciliation_run_id" UUID NOT NULL, "rule_code" VARCHAR(80) NOT NULL, "currency_code" CHAR(3) NOT NULL, "variance_amount" DECIMAL(20,6) NOT NULL DEFAULT 0, "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "reconciliation_matches_pkey" PRIMARY KEY ("id"));
CREATE TABLE "reconciliation_match_items" ("id" UUID NOT NULL, "reconciliation_match_id" UUID NOT NULL, "transaction_id" UUID NOT NULL, "side" VARCHAR(10) NOT NULL, "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "reconciliation_match_items_pkey" PRIMARY KEY ("id"));
CREATE TABLE "reconciliation_exceptions" ("id" UUID NOT NULL, "organization_id" UUID NOT NULL, "legal_entity_id" UUID NOT NULL, "reconciliation_run_id" UUID NOT NULL, "transaction_id" UUID, "exception_type" VARCHAR(80) NOT NULL, "severity" "ExceptionSeverity" NOT NULL DEFAULT 'MEDIUM', "status" "ExceptionStatus" NOT NULL DEFAULT 'OPEN', "currency_code" CHAR(3), "exposure_amount" DECIMAL(20,6), "description" VARCHAR(1000) NOT NULL, "assigned_to_user_id" UUID, "due_at" TIMESTAMPTZ(6), "resolved_at" TIMESTAMPTZ(6), "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMPTZ(6) NOT NULL, CONSTRAINT "reconciliation_exceptions_pkey" PRIMARY KEY ("id"));
CREATE INDEX "reconciliation_matches_reconciliation_run_id_idx" ON "reconciliation_matches"("reconciliation_run_id");
CREATE UNIQUE INDEX "reconciliation_match_items_reconciliation_match_id_transaction_id_key" ON "reconciliation_match_items"("reconciliation_match_id", "transaction_id");
CREATE INDEX "reconciliation_match_items_transaction_id_idx" ON "reconciliation_match_items"("transaction_id");
CREATE INDEX "reconciliation_exceptions_organization_id_status_severity_idx" ON "reconciliation_exceptions"("organization_id", "status", "severity");
CREATE INDEX "reconciliation_exceptions_reconciliation_run_id_idx" ON "reconciliation_exceptions"("reconciliation_run_id");
ALTER TABLE "reconciliation_matches" ADD CONSTRAINT "reconciliation_matches_reconciliation_run_id_fkey" FOREIGN KEY ("reconciliation_run_id") REFERENCES "reconciliation_runs"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "reconciliation_match_items" ADD CONSTRAINT "reconciliation_match_items_reconciliation_match_id_fkey" FOREIGN KEY ("reconciliation_match_id") REFERENCES "reconciliation_matches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "reconciliation_match_items" ADD CONSTRAINT "reconciliation_match_items_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "reconciliation_exceptions" ADD CONSTRAINT "reconciliation_exceptions_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "reconciliation_exceptions" ADD CONSTRAINT "reconciliation_exceptions_organization_id_legal_entity_id_fkey" FOREIGN KEY ("organization_id", "legal_entity_id") REFERENCES "legal_entities"("organization_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "reconciliation_exceptions" ADD CONSTRAINT "reconciliation_exceptions_reconciliation_run_id_fkey" FOREIGN KEY ("reconciliation_run_id") REFERENCES "reconciliation_runs"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "reconciliation_exceptions" ADD CONSTRAINT "reconciliation_exceptions_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
