import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { ExceptionStatus, ReconciliationPeriodStatus, ReconciliationRunStatus } from '@prisma/client';
import type { AuthenticatedUser } from '../auth/auth-user.interface.js';
import { AuditService } from '../audit/audit.service.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreatePeriodDto } from './periods.dto.js';
@Injectable()
export class PeriodsService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService) {}
  private async scope(org: string, user: AuthenticatedUser) { if (!user.roles.some((role) => role.code === 'PLATFORM_ADMIN' && role.organizationId === null) && !user.organizationIds.includes(org)) throw new NotFoundException('Organization not found'); if (!await this.prisma.organization.findUnique({ where: { id: org }, select: { id: true } })) throw new NotFoundException('Organization not found'); }
  async list(org: string, user: AuthenticatedUser) { await this.scope(org, user); return this.prisma.reconciliationPeriod.findMany({ where: { organizationId: org }, orderBy: { periodStart: 'desc' } }); }
  async create(org: string, dto: CreatePeriodDto, user: AuthenticatedUser) { await this.scope(org, user); const start = new Date(dto.periodStart); const end = new Date(dto.periodEnd); if (end < start) throw new BadRequestException('Period end date must not precede start date'); const overlap = await this.prisma.reconciliationPeriod.findFirst({ where: { organizationId: org, periodStart: { lte: end }, periodEnd: { gte: start } }, select: { id: true } }); if (overlap) throw new ConflictException('Reconciliation periods may not overlap'); const period = await this.prisma.reconciliationPeriod.create({ data: { organizationId: org, name: dto.name.trim(), periodStart: start, periodEnd: end } }); await this.audit.record({ organizationId: org, actorUserId: user.id, action: 'RECONCILIATION_PERIOD_CREATED', entityType: 'ReconciliationPeriod', entityId: period.id, after: { name: period.name, periodStart: period.periodStart.toISOString(), periodEnd: period.periodEnd.toISOString() } }); return period; }
  async close(org: string, id: string, user: AuthenticatedUser) { await this.scope(org, user); const period = await this.prisma.reconciliationPeriod.findFirst({ where: { id, organizationId: org }, select: { id: true, status: true, periodStart: true, periodEnd: true } }); if (!period) throw new NotFoundException('Reconciliation period not found'); if (period.status !== ReconciliationPeriodStatus.OPEN) throw new BadRequestException('Only open periods can be closed'); const [runs, openExceptions] = await Promise.all([this.prisma.reconciliationRun.count({ where: { organizationId: org, periodStart: { gte: period.periodStart }, periodEnd: { lte: period.periodEnd }, status: { in: [ReconciliationRunStatus.COMPLETED, ReconciliationRunStatus.COMPLETED_WITH_EXCEPTIONS] } } }), this.prisma.reconciliationException.count({ where: { organizationId: org, status: { not: ExceptionStatus.RESOLVED }, reconciliationRun: { periodStart: { gte: period.periodStart }, periodEnd: { lte: period.periodEnd } } } })]); if (!runs) throw new BadRequestException('At least one completed reconciliation run is required'); if (openExceptions) throw new BadRequestException('Resolve all period exceptions before closing'); const closed = await this.prisma.reconciliationPeriod.update({ where: { id: period.id }, data: { status: ReconciliationPeriodStatus.CLOSED, closedAt: new Date(), closedByUserId: user.id } }); await this.audit.record({ organizationId: org, actorUserId: user.id, action: 'RECONCILIATION_PERIOD_CLOSED', entityType: 'ReconciliationPeriod', entityId: closed.id, after: { status: closed.status } }); return closed; }
}
